<?php $conf = ivPool::get('conf'); ?>
<div class="bodyContent narrow">
	<h1>创建缩略图</h1>

	<?php if (!in_array('noteThumbs', ivPool::get('notes'))): ?>
		<div class="note">
			<a id="noteThumbs" href="#" class="close">&times;</a>
			<a class="iv-ext" title="如何创建缩略图" target="_blank" href="http://imagevuex.com/documentation/create-thumbnails/">如何创建缩略图</a>
		</div>
	<?php endif; ?>

	<form action="" method="post">
	<fieldset>
		<div class="row last">
			起始文件夹
			<select name="publishData[path]">
				<?php foreach ($this->folderTreeIterator as $folder):?>
					<option value="<?php echo $folder->getPrimary(); ?>" <?php echo (ivFilepath::directory($this->path) == $folder->getPrimary() ? 'selected="selected"' : ''); ?>><?php echo str_repeat('--', $this->folderTreeIterator->getDepth()); ?> <?php echo smartStripTagsSubstr($folder->getTitle()); ?>&nbsp;&nbsp;</option>
				<?php endforeach; ?>
			</select>
		</div>

	</fieldset>

	<fieldset>
		<div class="row">
			<label class="inline">
				宽度：
				<input type="text" class="text thumbSize" name="publishData[width]" value="<?php echo ($conf->get('/config/imagevue/thumbnails/thumbnail/boxwidth')); ?>" />
			</label>
			&nbsp;&nbsp;&nbsp;
			<label class="inline">
				高度：
				<input type="text" class="text thumbSize" name="publishData[height]" value="<?php echo ($conf->get('/config/imagevue/thumbnails/thumbnail/boxheight')); ?>" />
			</label>

		</div>
		<div class="row last">
			<label class="inline">
				<input type="radio" class="radio" name="publishData[resizetype]" value="<?php echo (ivImage::IMAGE_RESIZETYPE_CROPTOBOX); ?>" <?php echo (ivImage::IMAGE_RESIZETYPE_CROPTOBOX == $conf->get('/config/imagevue/thumbnails/thumbnail/resizetype') ? 'checked="checked"' : ''); ?> /> 裁剪模式
			</label>
			&nbsp;&nbsp;&nbsp;
			<label class="inline">
				<input type="radio" class="radio" name="publishData[resizetype]" value="<?php echo (ivImage::IMAGE_RESIZETYPE_RESIZETOBOX); ?>" <?php echo (ivImage::IMAGE_RESIZETYPE_RESIZETOBOX == $conf->get('/config/imagevue/thumbnails/thumbnail/resizetype') ? 'checked="checked"' : ''); ?> /> 缩放模式
			</label>
		</div>
	</fieldset>


	<fieldset>
		<div class="row">
			<label class="inline">
				<input name="publishData[thumbnails]" value="create" type="radio"  class="radio" checked="checked"/>
				创建缺失的缩略图
			</label>
		</div>
		<div class="row last">
			<label  class="inline">
				<input name="publishData[thumbnails]"  value="recreate" type="radio" class="radio" />
				重建所有缩略图
			</label>
		</div>
	</fieldset>

	<div class="controls">
		<input type="submit" class="buttonSave" value="创建" />
	</div>
</form>
</div>