<div  class="bodyContent narrow">
	<h1>用户管理</h1>

	<?php if (!in_array('noteUsers', ivPool::get('notes'))): ?>
		<div class="note">
			<a id="noteUsers" href="#" class="close">&times;</a>
			你可以添加多个拥有 Imagevue 控制面板权限的用户。
			<a title="Imagevue 用户管理" href="http://imagevuex.com/documentation/settings-page/" class="iv-ext" target="_blank">用户页面</a>
		</div>
	<?php endif; ?>

	<!-- #user -->

	<div class="controls left">
		<a href="?c=user&amp;a=edit" class="button buttonNew">添加用户</a>
	</div>

        <table class="nice">
			<thead>
				<th>用户</td>
				<th>权限</td>
				<th>&nbsp;</td>
			</thead>

			<?php
				$i = 0;
				foreach ($this->users as $user):
					if (ivAcl::isAdmin($user->login)):
						$i++;
					?>

					<tr>
						<td><a title="编辑" href="?c=user&amp;a=edit&amp;login=<?php echo $user->login ?>"><?php echo ($this->user == $user->login ? '<b>'.$user->login.'<b>' : $user->login ); ?></a></td>
							<td></td>
						<td>
							<a  class="button buttonEdit" title="编辑" href="?c=user&amp;a=edit&amp;login=<?php echo $user->login ?>">编辑</a>
							<a class="button buttonDelete" title="删除" href="?c=user&amp;a=delete&amp;login=<?php echo $user->login ?>" onclick="return confirm('您确认删除用户 <?php echo $user->login; ?>?');">删除</a>
						</td>
					</tr>

					<?php
					endif;
				endforeach;
				foreach ($this->users as $user):
					if (!ivAcl::isAdmin($user->login)):
						$i++;
					?>

					<tr class="<?php echo ($i % 2 ? 'odd' : ''); ?>">
						<td><a title="edit" href="?c=user&amp;a=edit&amp;login=<?php echo $user->login ?>"><?php echo $user->login ?></a></td>
						<td><?php echo $user->access; ?></td>
						<td>
							<a  class="button buttonEdit" title="Edit" href="?c=user&amp;a=edit&amp;login=<?php echo $user->login ?>">编辑</a>
						<a  class="button buttonDelete" title="Delete" href="?c=user&amp;a=delete&amp;login=<?php echo $user->login ?>">删除</a>
						</td>
					</tr>

					<?php
					endif;
				endforeach;
			?>

			</table>

				<div class="controls left">
					<a href="?c=user&amp;a=edit" class="button buttonNew">添加用户</a>
				</div>
</div>