<?php
	$this->placeholder->set('currentPath', $this->folder->getPrimary());
	$this->placeholder->set('currentTitle', $this->folder->getTitle());
	$this->placeholder->set('thumbRecreationPath', $this->folder->getPrimary());
?>

<?php if (!$this->folder->checkPassword(isset($_SESSION['imagevue']['password']) ? $_SESSION['imagevue']['password'] : null)): ?>
	<div class="password">
		<form action="" method="post">
			<label>Password protected folder</label>
			<input type="password" class="text" name="password"> <input type="submit" value="Unlock">
		</form>
	</div>
<?php else: ?>
	<?php if ($this->folder->isPage()): ?>
		<div class="textPage">
			<h1><?php echo $this->folder->getTitle(); ?></h1>
			<div>
				<?php echo replaceSnippets($this->folder->pageContent); ?>
			</div>
		</div>
	<?php else: ?>
		<div class="currentFolder">
			<?php if ($this->folder->Parent): ?>
				<div class="levelUp">
					<a href="?<?php echo urlencode($this->folder->Parent->getPrimary()); ?>">
						<img src="iv-includes/images/folder_parent.png" alt="前往父级文件夹" title="前往父级文件夹" /><br />
						<span class="textblock">..</span>
					</a>
				</div>
			<?php endif; ?>
			<div class="currentFolderTitle">
				<h1 class="title">
					<?php echo $this->folder->getTitle(); ?>
				</h1>
			   <h2 class="description">
					<?php echo $this->folder->description ?>
			   </h2>
			</div>
		</div>
		<div id="folders">
			<?php foreach ($this->folder->Folders as $item): ?>
				<?php if (!$item->isHidden()): ?>
					<?php if ($item->isLink()): ?>
						<?php
							$linkParams = explode('*', $item->pageContent, 2);
							$link = $linkParams[0];
							$target = isset($linkParams[1]) ? $linkParams[1] : '';
						?>
						<a href="<?php echo $link; ?>" <?php echo (empty($target) ? '' : "target=\"$target\"") ?> title="<?php echo strip_tags($item->getTitle()); ?> <?php echo strip_tags($item->description); ?>" >
					<?php else: ?>
						<a href="?<?php echo urlencode($item->getPrimary()); ?>"  title="<?php echo strip_tags($item->getTitle()); ?> <?php echo strip_tags($item->description); ?>" >
					<?php endif; ?>
						<img class="png" src="<?php echo $item->thumbnail; ?>" alt="<?php echo $item->name; ?>"/><br />
						<span class="textblock"><?php echo htmlspecialchars(strip_tags($item->getTitle())); ?></span>
					</a>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>

		<div id="thumbnails">
			<?php foreach ($this->folder->Files as $item): ?>
				<?php if (is_a($item, 'ivFileImage')): ?>
					<a rel="colorbox" href="<?php echo ($this->useLightview ? $item->getPrimary() : '?' . urlencode($item->getPrimary())) ?>" title="<?php echo strip_tags($item->getTitle()); ?> <?php echo strip_tags($item->description); ?>" style="width: <?php echo $this->folder->maxThumbWidth + 20; ?>px; height: <?php echo $this->folder->maxThumbHeight + 20; ?>px;">
						<span style="background: url('<?php echo str_replace("'", "\'", $item->thumbnail); ?>') center center no-repeat; width: <?php echo $this->folder->maxThumbWidth; ?>px; height: <?php echo $this->folder->maxThumbHeight; ?>px;" ></span>
					</a>
				<?php endif; ?>
			<?php endforeach; ?>
		</div>
	<?php endif; ?>
<?php endif; ?>

<?php if ($this->useLightview): ?>
<script type="text/javascript">
// <![CDATA[
	(function ($) {
		$(document).ready(function () {
			$("a[rel='colorbox']").colorbox();
		});
	})(jQuery);
// ]]>
</script>
<?php endif; ?>