<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<?php
	$conf = ivPool::get('conf');
	$keywords = $conf->get('/config/imagevue/seo/keywords');
	$description = $conf->get('/config/imagevue/seo/description');
	$counters = $conf->get('/config/imagevue/seo/counters');
?>
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="viewport" content="width=640" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<meta name="keywords" content="<?php echo $keywords; ?>" />
		<meta name="description" content="<?php echo $description; ?>" />
		<title>Site map [<?php echo $this->siteTitle; ?>]</title>
		<link href="<?php echo IV_PATH; ?>assets/dtree/css/dtree.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo IV_PATH; ?>assets/css/imagevue.html.css" rel="stylesheet" type="text/css" />
		<link media="only screen and (max-device-width: 480px)" href="<?php echo IV_PATH; ?>assets/css/imagevue.iphone.css.css" type="text/css" rel="stylesheet" />
		<?php if (!empty($_COOKIE['stylesheet'])): ?>
			<link href="<?php echo IV_PATH; ?>css/<?php echo $_COOKIE['stylesheet']; ?>" rel="stylesheet" type="text/css" />
		<?php endif; ?>
		<link href="<?php echo IV_PATH; ?>assets/css/imagevue.adminbar.css" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="<?php echo IV_PATH; ?>assets/dtree/js/dtree.js"></script>
	</head>
	<body>
		<?php if (ivAcl::isAdmin()): ?>
			<!-- #forAdmin -->
			<div id="forAdmin">
				<div class="right"><?php echo htmlspecialchars(ivAuth::getCurrentUserLogin()) ?>
					<a href="#" title="隐藏管理工具栏" onclick="document.getElementById('forAdmin').style.display = 'none'; return false;">&times; 隐藏</a>
				</div>
				<a href="<?php echo $conf->get('/config/imagevue/settings/adminfolder') ?>" title="相册管理/文件管理">相册管理 &raquo;</a>
				<a href="<?php echo $conf->get('/config/imagevue/settings/adminfolder') ?>?c=config" title="更改 <?php echo $this->siteTitle; ?> 设置">设置 &raquo;</a>
				<!-- <a href="?a=index">API 参考 &raquo;</a>  -->
			</div>
			<!-- /forAdmin -->
		<?php endif; ?>
		<div id="wrap">
		<!-- #header -->
		<div id="header"><?php echo $this->siteTitle; ?></div>
		<!-- /header -->

		<!-- #subheader -->
		<div id="subheader">

			<div id="flashlink">
				<a href="?p=gallery" title="Flash 相册">Flash 相册</a>
				|
				<a href="?p=html" title="HTML 相册">HTML 相册</a>
			</div>

			<div id="menu">
				<div>
					<img src="<?php echo IV_PATH; ?>images/plus_icon.png" alt="" class="openMenu"/>
				</div>
				<!-- JSTREE STARTS HERE -->
				<?php
					$contentFolder = ivMapperFactory::getMapper('folder')->find(ROOT_DIR . ivPath::canonizeRelative($conf->get('/config/imagevue/settings/contentfolder')));
					$iterator = new ivRecursiveFolderIterator($contentFolder);
					$filter1 = new ivRecursiveFolderIteratorVisible($iterator);
					$filter2 = new ivRecursiveFolderIteratorPassword($filter1, (isset($_SESSION['imagevue']['password']) ? (string) $_SESSION['imagevue']['password'] : null));
					$folderTreeIterator = new RecursiveIteratorIterator($filter2, RecursiveIteratorIterator::SELF_FIRST);
					echo $this->partial('tree', array('folderTreeIterator' => $folderTreeIterator));
				?>
				<!-- JSTREE ENDS HERE -->
			</div>

			<div class="clrFlt"></div>
		</div>
		<!-- /subheader -->

		<div id="content">
			<div class="textPage">
				<h1><?php echo $this->siteTitle?> 站点地图</h1>
				<?php if (count($this->folderTreeIterator)): ?>
					<?php $oldDepth = -1; ?>
					<?php foreach ($this->folderTreeIterator as $folder): ?>
						<?php if ($oldDepth < $this->folderTreeIterator->getDepth()): ?>
							<ul>
								<li>
						<?php elseif ($oldDepth > $this->folderTreeIterator->getDepth()): ?>
							<?php for ($i = 0; $i < $oldDepth - $this->folderTreeIterator->getDepth(); $i++): ?>
									</li>
								</ul>
							<?php endfor; ?>
							</li>
							<li>
						<?php else: ?>
							</li>
							<li>
						<?php endif; ?>
							<h2>
								<a href="?share=<?php echo ($folder->isLink() ? $folder->pageContent : '?' .  urlencode($folder->getPrimary())); ?>" title="<?php echo strip_tags($folder->description); ?>">
									<?php echo strip_tags($folder->getTitle()); ?>
								</a>
							</h2>
						<?php $oldDepth = $this->folderTreeIterator->getDepth(); ?>
						<?php if (!$folder->isPage() && !$folder->isLink()): ?>
							<?php if (count($folder->Files) && ($folder->checkPassword((isset($_SESSION['imagevue']['password']) ? $_SESSION['imagevue']['password'] : null)))): ?>
								<ul>
									<?php foreach ($folder->Files as $file): ?>
										<li>
											<h3>
												<a href="?share=<?php echo urlencode($file->getPrimary()); ?>" title="<?php echo strip_tags($file->description); ?>">
													<?php echo strip_tags($file->getTitle()); ?>
												</a>
											</h3>
										</li>
									<?php endforeach; ?>
								</ul>
							<?php endif; ?>
						<?php endif; ?>
					<?php endforeach; ?>
					<?php for ($i = -1; $i < $oldDepth; $i++): ?>
							</li>
						</ul>
					<?php endfor; ?>
				<?php endif; ?>
			</div>
		</div>
		<div id="counters">
			<?php echo $counters; ?>
		</div>
		</div>
		
	</body>
</html>